[tool.poetry]
name = "gmm"
version = "0.1.0"
description = ""
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.22.3"
scipy = "^1.8.0"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
svgutils = "^0.3.4"
ipykernel = "^6.9.0"
pyarrow = "^7.0.0"
tensorly = "0.7.0"
xarray = "^2022.3.0"
autopep8 = "^1.6.0"
jaxlib = "0.3.0"
jax = "0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "gmm.figures.common:genFigure"
