[tool.poetry]
name = "gmm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.22.2"
scipy = "^1.8.0"
scikit-learn = "^1.0.2"
seaborn = "^0.11.2"
svgutils = "^0.3.4"
ipykernel = "^6.9.0"
pyarrow = "^7.0.0"
pomegranate = "^0.14.7"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "gmm.figures.common:genFigure"
